backend:
  name: git-gateway
  branch: main # o el nombre de tu rama principal

media_folder: "public/images/posts"
public_folder: "/images/posts"

collections:
  - name: "blog"
    label: "Blog"
    folder: "public/images/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

# Asegúrate de que esta línea esté presente y correcta
publish_mode: editorial_workflow